# BUILD
FROM node:16-alpine as builder

RUN apk add --no-cache bash git python3 perl alpine-sdk

WORKDIR /opt/app

COPY . .

RUN cd telepathy-agent && \
    npm ci && \
    npm run binary:linux:alpine


# RUN
FROM alpine

COPY --from=builder /opt/app/telepathy-agent/dist/telepathy-agent-linux-alpine /usr/bin/telepathy-agent

RUN apk add libstdc++ libgcc && \
    mkdir /workspace

WORKDIR /workspace

CMD [ "/usr/bin/telepathy-agent" ]