# BUILD
FROM node:14-alpine as builder

RUN apk add --no-cache bash git python perl alpine-sdk

WORKDIR /opt/app

COPY . .

RUN cd telepathy-agent && \
    npm ci && \
    npm run binary:linux:x64


# RUN
FROM node:14-alpine

COPY --from=builder /opt/app/telepathy-agent/dist/telepathy-agent-linux-x64 /usr/bin/telepathy-agent

RUN mkdir /workspace
WORKDIR /workspace

CMD [ "/usr/bin/telepathy-agent" ]
