# BUILD
FROM node:14-alpine as builder

RUN apk add --no-cache bash git python perl alpine-sdk

WORKDIR /opt/app

COPY . .

RUN cd telepathy-server && \
    npm ci && \
    npm rebuild bcrypt --build-from-source && \
    npm run binary:linux:alpine


# RUN
FROM alpine

COPY --from=builder /opt/app/telepathy-server/dist/telepathy-server-linux-alpine /usr/bin/telepathy-server

RUN apk add libstdc++ libgcc && \
    mkdir /workspace

WORKDIR /workspace

CMD [ "/usr/bin/telepathy-server" ]
