# BUILD
FROM node:14-alpine as builder

RUN apk add --no-cache bash git python perl alpine-sdk

WORKDIR /opt/app

COPY . .

RUN cd telepathy-server && \
    npm ci && \
    npm run binary:linux:x64


# RUN
FROM node:14-alpine

COPY --from=builder /opt/app/telepathy-server/dist/telepathy-server-linux-x64 /usr/bin/telepathy-server

RUN mkdir /workspace
WORKDIR /workspace

CMD [ "/usr/bin/telepathy-server" ]
