# BUILD
FROM node:16 as builder

WORKDIR /opt/app

COPY . .

RUN cd telepathy-server && \
    npm ci && \
    npm run build


# RUN
FROM node:16-ubuntu

COPY --from=builder /opt/app/telepathy-server/dist /opt/app/dist
COPY --from=builder /opt/app/telepathy-server/node_modules /opt/app/node_modules

WORKDIR /opt/app

CMD [ "node", "dist/app.js" ]
