# BUILD
FROM node:16-alpine as builder

RUN apk add --no-cache bash git python perl alpine-sdk

WORKDIR /opt/app

COPY . .

RUN cd telepathy-agent && \
    npm install && \
    npm run build


# RUN
FROM node:16-alpine

COPY --from=builder /opt/app/telepathy-agent/node_modules /opt/app/telepathy-agent/node_modules
COPY --from=builder /opt/app/telepathy-agent/dist /opt/app/telepathy-agent/dist
COPY _shared/docker_entrypoint_agent.sh /docker_entrypoint_agent.sh

RUN chmod +x /docker_entrypoint_agent.sh && \
    mkdir /workspace

WORKDIR /workspace

CMD [ "/docker_entrypoint_agent.sh" ]
