# BUILD
FROM node:14-alpine as builder

RUN apk add --no-cache bash git python perl alpine-sdk

WORKDIR /opt/app

COPY ./telepathy-web .

RUN export CYPRESS_INSTALL_BINARY=0 && \
    npm ci && \
    npm run lint && \
    npm run build

# Running
FROM nginx:latest

RUN rm -fr /etc/nginx/site-enabled/default.conf
RUN rm -fr /etc/nginx/conf.d/default.conf

COPY --from=builder /opt/app/dist /usr/share/nginx/html
COPY ./telepathy-web/docker/nginx/default.conf /etc/nginx/site-enabled/
COPY ./telepathy-web/docker/nginx/default.conf /etc/nginx/conf.d/
COPY ./telepathy-web/docker/entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]
