# BUILD
FROM node:14-alpine as builder

RUN apk add --no-cache bash git python perl alpine-sdk

WORKDIR /opt/app

COPY . .

RUN cd telepathy-agent && \
    npm ci && \
    npm audit  && \
    npm run lint && \
    npm run test && \
    npm run build


# RUN
FROM node:14-alpine

COPY --from=builder /opt/app/telepathy-agent/dist /opt/app/dist
COPY --from=builder /opt/app/telepathy-agent/node_modules /opt/app/node_modules

WORKDIR /opt/app

CMD [ "node", "dist/app.js" ]
