version: "3"

services:
  server:
    build: .
    image: ${DOCKER_REGISTRY}/telepathy-client_app
    networks:
      webproxy-network:
        aliases:
          - example

networks:
  webproxy-network:
    external: true
