version: "3"

services:
  app:
    build: .
    image: ${DOCKER_REGISTRY}/telepathy-client_app
    volumes:
      - ../src:/opt/app/src
      - ../tsconfig.json:/opt/app/tsconfig.json
      - ../package.json:/opt/app/package.json
      - ../package-lock.json:/opt/app/package-lock.json
      - ./start-cmd-dev.sh:/start-cmd.sh
      - ./config-sample.json:/etc/telepathy/config.json
