version: '3'

services:

  server:
    build: .
    image: ${DOCKER_REGISTRY}/example_server
    labels:
      - "discovery.service.name=example.com"
      - "discovery.service.port=80"
      - "discovery.service.https=y"
    networks:
      webproxy-network:
        aliases:
          - example

networks:
  webproxy-network:
    external: true
